// AUTO-GENERATED — DO NOT EDIT.
// Regenerated on every `pnpm tauri dev` (debug) and via
// `cargo test --test ipc_bindings` (CI drift check). See
// docs/adr/0007-ipc-typegen.md.

/* eslint-disable */

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**
	 *  Returns an application health report.
	 * 
	 *  Used by the frontend on startup to verify that the webview, command
	 *  bridge, and database are all alive.
	 */
	health: () => typedError<HealthReport, AppError>(__TAURI_INVOKE("health")),
	setTwitchCredentials: (input: SetTwitchCredentialsInput) => typedError<CredentialsStatus, AppError>(__TAURI_INVOKE("set_twitch_credentials", { input })),
	getTwitchCredentialsStatus: () => typedError<CredentialsStatus, AppError>(__TAURI_INVOKE("get_twitch_credentials_status")),
	clearTwitchCredentials: () => typedError<null, AppError>(__TAURI_INVOKE("clear_twitch_credentials")),
	addStreamer: (input: AddStreamerInput) => typedError<StreamerSummary, AppError>(__TAURI_INVOKE("add_streamer", { input })),
	removeStreamer: (input: RemoveStreamerInput) => typedError<null, AppError>(__TAURI_INVOKE("remove_streamer", { input })),
	listStreamers: () => typedError<StreamerSummary[], AppError>(__TAURI_INVOKE("list_streamers")),
	listVods: (input: ListVodsInput) => typedError<VodWithChapters[], AppError>(__TAURI_INVOKE("list_vods", { input })),
	getVod: (input: GetVodInput) => typedError<VodWithChapters, AppError>(__TAURI_INVOKE("get_vod", { input })),
	getSettings: () => typedError<AppSettings, AppError>(__TAURI_INVOKE("get_settings")),
	updateSettings: (patch: SettingsPatch) => typedError<AppSettings, AppError>(__TAURI_INVOKE("update_settings", { patch })),
	triggerPoll: (input: TriggerPollInput) => typedError<null, AppError>(__TAURI_INVOKE("trigger_poll", { input })),
	getPollStatus: () => typedError<PollStatusRow[], AppError>(__TAURI_INVOKE("get_poll_status")),
	enqueueDownload: (input: EnqueueDownloadInput) => typedError<DownloadRow, AppError>(__TAURI_INVOKE("enqueue_download", { input })),
	pauseDownload: (input: VodIdInput) => typedError<DownloadRow, AppError>(__TAURI_INVOKE("pause_download", { input })),
	resumeDownload: (input: VodIdInput) => typedError<DownloadRow, AppError>(__TAURI_INVOKE("resume_download", { input })),
	cancelDownload: (input: VodIdInput) => typedError<DownloadRow, AppError>(__TAURI_INVOKE("cancel_download", { input })),
	retryDownload: (input: VodIdInput) => typedError<DownloadRow, AppError>(__TAURI_INVOKE("retry_download", { input })),
	reprioritizeDownload: (input: ReprioritizeInput) => typedError<DownloadRow, AppError>(__TAURI_INVOKE("reprioritize_download", { input })),
	listDownloads: (input: ListDownloadsInput) => typedError<DownloadRow[], AppError>(__TAURI_INVOKE("list_downloads", { input })),
	getDownload: (input: VodIdInput) => typedError<DownloadRow, AppError>(__TAURI_INVOKE("get_download", { input })),
	getStagingInfo: () => typedError<StagingInfo, AppError>(__TAURI_INVOKE("get_staging_info")),
	getLibraryInfo: () => typedError<LibraryInfo, AppError>(__TAURI_INVOKE("get_library_info")),
	migrateLibrary: (input: MigrateLibraryInput) => typedError<MigrateLibraryOutput, AppError>(__TAURI_INVOKE("migrate_library", { input })),
	getMigrationStatus: (input: MigrationIdInput) => typedError<MigrationRow, AppError>(__TAURI_INVOKE("get_migration_status", { input })),
	listTimeline: (input: ListTimelineInput) => typedError<Interval[], AppError>(__TAURI_INVOKE("list_timeline", { input })),
	getCoStreams: (input: GetCoStreamsInput) => typedError<CoStream[], AppError>(__TAURI_INVOKE("get_co_streams", { input })),
	getTimelineStats: () => typedError<TimelineStats, AppError>(__TAURI_INVOKE("get_timeline_stats")),
	rebuildTimelineIndex: () => typedError<TimelineStats, AppError>(__TAURI_INVOKE("rebuild_timeline_index")),
	getAppSummary: () => typedError<AppSummary, AppError>(__TAURI_INVOKE("get_app_summary")),
	pauseAllDownloads: () => typedError<number, AppError>(__TAURI_INVOKE("pause_all_downloads")),
	resumeAllDownloads: () => typedError<number, AppError>(__TAURI_INVOKE("resume_all_downloads")),
	setWindowCloseBehavior: (input: SetWindowCloseBehaviorInput) => typedError<null, AppError>(__TAURI_INVOKE("set_window_close_behavior", { input })),
	toggleStreamerFavorite: (input: ToggleFavoriteInput) => typedError<boolean, AppError>(__TAURI_INVOKE("toggle_streamer_favorite", { input })),
	/**
	 *  Broadcast a shutdown request with a 10 s drain deadline. Services
	 *  subscribe to this event via their existing `.shutdown()` handles;
	 *  the webview can show a "saving state…" toast until the process
	 *  actually exits.
	 */
	requestShutdown: () => typedError<null, AppError>(__TAURI_INVOKE("request_shutdown")),
	/**
	 *  Called by the tray menu handlers to emit a uniform webview event.
	 *  Always succeeds — emission errors are logged and swallowed.
	 */
	emitTrayAction: (input: TrayActionInput) => typedError<null, AppError>(__TAURI_INVOKE("emit_tray_action", { input })),
	listShortcuts: () => typedError<Shortcut[], AppError>(__TAURI_INVOKE("list_shortcuts")),
	setShortcut: (input: SetShortcutInput) => typedError<Shortcut[], AppError>(__TAURI_INVOKE("set_shortcut", { input })),
	resetShortcuts: () => typedError<Shortcut[], AppError>(__TAURI_INVOKE("reset_shortcuts")),
	/**
	 *  Fetch the asset bundle for a single VOD. Returns a struct with
	 *  every `Option<String>` field set to `None` if the VOD has no
	 *  completed download — that's the expected state for a VOD the user
	 *  hasn't enqueued yet, not an error.
	 */
	getVodAssets: (input: VodAssetsInput) => typedError<VodAssets, AppError>(__TAURI_INVOKE("get_vod_assets", { input })),
	/**
	 *  Force-regenerate the single-frame thumbnail for a VOD. Useful for
	 *  pre-Phase-5 rows that were downloaded before the preview pipeline
	 *  existed and the thumbnail is missing. Returns when ffmpeg exits
	 *  (success or failure — failure surfaces as `AppError::Sidecar`).
	 */
	regenerateVodThumbnail: (input: VodAssetsInput) => typedError<null, AppError>(__TAURI_INVOKE("regenerate_vod_thumbnail", { input })),
	/**
	 *  Return a `VideoSource` narrowed to `ready | missing | partial`.
	 *  The player uses this as its single choke point — the renderer
	 *  never builds a filesystem path directly.
	 */
	getVideoSource: (input: VodAssetsInput) => typedError<VideoSource, AppError>(__TAURI_INVOKE("get_video_source", { input })),
	/**
	 *  Remux the downloaded `.mp4` in-place via ffmpeg. The player's
	 *  "Remux file" recovery action fires this when the `<video>`
	 *  element can't decode the downloaded file.
	 */
	requestRemux: (input: VodAssetsInput) => typedError<null, AppError>(__TAURI_INVOKE("request_remux", { input })),
	getWatchProgress: (input: WatchVodIdInput) => typedError<{
	vodId: string,
	positionSeconds: number,
	durationSeconds: number,
	watchedFraction: number,
	state: WatchState,
	firstWatchedAt: number | null,
	lastWatchedAt: number,
	lastSessionDurationSeconds: number,
	totalWatchSeconds: number,
} | null, AppError>(__TAURI_INVOKE("get_watch_progress", { input })),
	updateWatchProgress: (input: UpdateWatchProgressInput) => typedError<WatchProgressRow, AppError>(__TAURI_INVOKE("update_watch_progress", { input })),
	markWatched: (input: WatchVodIdInput) => typedError<WatchProgressRow, AppError>(__TAURI_INVOKE("mark_watched", { input })),
	markUnwatched: (input: WatchVodIdInput) => typedError<WatchProgressRow, AppError>(__TAURI_INVOKE("mark_unwatched", { input })),
	listContinueWatching: (input: ListContinueWatchingInput) => typedError<ContinueWatchingEntry[], AppError>(__TAURI_INVOKE("list_continue_watching", { input })),
	getWatchStats: (input: GetWatchStatsInput) => typedError<WatchStats, AppError>(__TAURI_INVOKE("get_watch_stats", { input })),
	getAutostartStatus: () => typedError<AutostartStatus, AppError>(__TAURI_INVOKE("get_autostart_status")),
	setAutostart: (input: SetAutostartInput) => typedError<AutostartStatus, AppError>(__TAURI_INVOKE("set_autostart", { input })),
	openSyncGroup: (input: OpenSyncGroupInput) => typedError<SyncSession, AppError>(__TAURI_INVOKE("open_sync_group", { input })),
	closeSyncGroup: (input: SyncSessionIdInput) => typedError<null, AppError>(__TAURI_INVOKE("close_sync_group", { input })),
	getSyncGroup: (input: SyncSessionIdInput) => typedError<SyncSession, AppError>(__TAURI_INVOKE("get_sync_group", { input })),
	setSyncLeader: (input: SetSyncLeaderInput) => typedError<SyncSession, AppError>(__TAURI_INVOKE("set_sync_leader", { input })),
	syncSeek: (input: SyncSeekInput) => typedError<null, AppError>(__TAURI_INVOKE("sync_seek", { input })),
	syncPlay: (input: SyncSessionIdInput) => typedError<null, AppError>(__TAURI_INVOKE("sync_play", { input })),
	syncPause: (input: SyncSessionIdInput) => typedError<null, AppError>(__TAURI_INVOKE("sync_pause", { input })),
	syncSetSpeed: (input: SyncSetSpeedInput) => typedError<null, AppError>(__TAURI_INVOKE("sync_set_speed", { input })),
	getOverlap: (input: GetOverlapInput) => typedError<OverlapResult, AppError>(__TAURI_INVOKE("get_overlap", { input })),
	recordSyncDrift: (input: RecordSyncDriftInput) => typedError<null, AppError>(__TAURI_INVOKE("record_sync_drift", { input })),
	reportSyncOutOfRange: (input: ReportSyncOutOfRangeInput) => typedError<null, AppError>(__TAURI_INVOKE("report_sync_out_of_range", { input })),
	getCleanupPlan: () => typedError<CleanupPlan, AppError>(__TAURI_INVOKE("get_cleanup_plan")),
	executeCleanup: (input: ExecuteCleanupInput) => typedError<CleanupResult, AppError>(__TAURI_INVOKE("execute_cleanup", { input })),
	getCleanupHistory: (input: CleanupHistoryInput) => typedError<CleanupLogEntry[], AppError>(__TAURI_INVOKE("get_cleanup_history", { input })),
	getDiskUsage: () => typedError<DiskUsage, AppError>(__TAURI_INVOKE("get_disk_usage")),
	checkForUpdate: (input: CheckForUpdateInput) => typedError<{
	version: string,
	releaseUrl: string,
	body: string,
	publishedAt: number | null,
} | null, AppError>(__TAURI_INVOKE("check_for_update", { input })),
	getUpdateStatus: () => typedError<UpdateStatus, AppError>(__TAURI_INVOKE("get_update_status")),
	skipUpdateVersion: (input: SkipUpdateVersionInput) => typedError<null, AppError>(__TAURI_INVOKE("skip_update_version", { input })),
	/**
	 *  Open an http(s) URL in the user's default browser.  Used by the
	 *  "View release" button on the update banner.  Defence-in-depth:
	 *  the URL is parsed via [`url::Url::parse`] so a string like
	 *  `https://\x00evil.com` (which would pass a naive prefix check
	 *  but truncate at the OS-layer `open` call) is rejected.  We also
	 *  enforce a `github.com` host allow-list since the only sanctioned
	 *  caller is the updater service whose data flows from
	 *  `https://api.github.com/repos/.../releases/latest`.
	 */
	openReleaseUrl: (input: OpenReleaseUrlInput) => typedError<null, AppError>(__TAURI_INVOKE("open_release_url", { input })),
	/**
	 *  Persisted encoder-capability snapshot (or `None` if detection has
	 *  never run).  Returns the raw `EncoderCapability` blob — the
	 *  renderer renders the per-encoder-kind labels.
	 */
	getEncoderCapability: () => typedError<{
	/**
	 *  Encoder the service will use first.  When this is
	 *  [`EncoderKind::Software`] but `software_encode_opt_in = 0`
	 *  in settings, the re-encode pass refuses to run and surfaces
	 *  an error instead.
	 */
	primary: EncoderKind,
	/**
	 *  Every encoder that passed both the `-encoders` listing AND
	 *  the runtime test encode.  Always contains [`EncoderKind::Software`]
	 *  in the fallback position because libx265 is bundled with
	 *  every ffmpeg sidecar build (ADR-0013).
	 */
	available: EncoderKind[],
	// Whether the primary encoder supports H.265.
	h265: boolean,
	// Whether the primary encoder supports H.264.
	h264: boolean,
	/**
	 *  Wall-clock seconds at which the detection ran.  Used by the
	 *  Settings UI to render "Auto-detected (NN minutes ago)".
	 */
	testedAt: number,
} | null, AppError>(__TAURI_INVOKE("get_encoder_capability")),
	/**
	 *  Force a fresh detection probe (`ffmpeg -encoders` + 2-second test
	 *  encode).  Persists the new capability and returns it.  Triggered
	 *  by the Settings UI's "Re-detect" button.
	 */
	redetectEncoders: () => typedError<EncoderCapability, AppError>(__TAURI_INVOKE("redetect_encoders")),
	setVideoQualityProfile: (input: SetVideoQualityProfileInput) => typedError<VideoQualityProfile, AppError>(__TAURI_INVOKE("set_video_quality_profile", { input })),
	pickVod: (input: PickVodInput) => typedError<PickResult, AppError>(__TAURI_INVOKE("pick_vod", { input })),
	pickNextN: (input: PickNextNInput) => typedError<string[], AppError>(__TAURI_INVOKE("pick_next_n", { input })),
	unpickVod: (input: PickVodInput) => typedError<PickResult, AppError>(__TAURI_INVOKE("unpick_vod", { input })),
	setDistributionMode: (input: SetDistributionModeInput) => typedError<DistributionMode, AppError>(__TAURI_INVOKE("set_distribution_mode", { input })),
	setSlidingWindowSize: (input: SetSlidingWindowSizeInput) => typedError<number, AppError>(__TAURI_INVOKE("set_sliding_window_size", { input })),
};

/* Types */
export type AddStreamerInput = {
	login: string,
};

/**
 *  Typed application error. Serialized with a `kind` tag so the frontend
 *  can exhaustively narrow on it via a discriminated union.
 */
export type AppError = { kind: "db"; detail: string } | { kind: "io"; detail: string } | { kind: "invalid_input"; detail: string } | { kind: "not_found" } | { kind: "internal"; detail: string } | 
// Credentials-related failure (keychain read/write, missing creds, invalid input shape).
{ kind: "credentials"; detail: string } | 
// Twitch App Access Token acquisition / refresh failed.
{ kind: "twitch_auth"; detail: string } | 
/**
 *  Twitch rate limit hit. `retry_after_seconds` is a conservative hint
 *  derived from the `Ratelimit-Reset` header (or a policy floor).
 */
{ kind: "twitch_rate_limit"; retry_after_seconds: number } | 
// Generic Twitch Helix API error (non-rate-limit HTTP failure).
{ kind: "twitch_api"; status: number; detail: string } | 
// Helix returned 404 / empty set for a user or video that should exist.
{ kind: "twitch_not_found"; detail: string } | 
/**
 *  Twitch GraphQL endpoint failure. Separately typed so the UI can
 *  surface "chapters unavailable" differently from Helix failures.
 */
{ kind: "twitch_gql"; detail: string } | 
// VOD ingest pipeline failure (persistence, chapter merge, etc.).
{ kind: "ingest"; detail: string } | 
// Parser failure — duration, chapter payload, ISO timestamp.
{ kind: "parse"; detail: string } | 
/**
 *  A download-queue operation failed (state-machine violation,
 *  row not found, invalid priority, etc.). Subprocess failures
 *  surface as [`AppError::Sidecar`] instead.
 */
{ kind: "download"; detail: string } | 
/**
 *  A bundled sidecar (`yt-dlp`, `ffmpeg`) returned a non-zero exit
 *  code or couldn't be located / spawned. `tool` distinguishes the
 *  two for UI routing.
 */
{ kind: "sidecar"; tool: string; detail: string } | 
/**
 *  Disk-space preflight failed — either the staging or library
 *  partition had too little free space for the estimated download
 *  size. The frontend surfaces this with a "free up space" CTA.
 */
{ kind: "disk_full"; path: string } | 
/**
 *  Library-layout migration failed at the filesystem level (move,
 *  copy+verify, or sidecar write). Individual per-file errors are
 *  logged; this variant reports the overall failure to the user.
 */
{ kind: "library_migration"; detail: string } | 
/**
 *  Auto-cleanup operation failed before any deletion happened
 *  (settings inversion, missing library_root, no probe data).
 *  Per-file deletion errors are aggregated into the
 *  `partial`/`error` status on the cleanup_log row instead.
 */
{ kind: "cleanup"; detail: string } | 
/**
 *  Update-checker operation failed (network, parse, semver
 *  comparison).  Surfaced verbatim to the Settings UI's
 *  "Couldn't reach GitHub" line.
 */
{ kind: "update_check"; detail: string };

export type AppReadyEvent = {
	startedAt: number,
};

export type AppSettings = {
	enabledGameIds: string[],
	pollFloorSeconds: number,
	pollRecentSeconds: number,
	pollCeilingSeconds: number,
	concurrencyCap: number,
	firstBackfillLimit: number,
	credentials: CredentialsStatus,
	/**
	 *  Absolute path the user chose as library root. `None` until
	 *  the user picks one via the Settings UI folder picker.
	 */
	libraryRoot: string | null,
	libraryLayout: LibraryLayoutKind,
	// Optional override. `None` means "use the platform default".
	stagingPath: string | null,
	maxConcurrentDownloads: number,
	// `None` = unlimited.
	bandwidthLimitBps: number | null,
	qualityPreset: QualityPreset,
	autoUpdateYtDlp: boolean,
	windowCloseBehavior: WindowCloseBehavior,
	startAtLogin: boolean,
	showDockIcon: boolean,
	notificationsEnabled: boolean,
	notifyDownloadComplete: boolean,
	notifyDownloadFailed: boolean,
	notifyFavoritesIngest: boolean,
	notifyStorageLow: boolean,
	/**
	 *  Fraction in `[0.7, 1.0]` at which the watch-progress state
	 *  machine transitions `in_progress → completed`. Persisted in
	 *  `app_settings.completion_threshold` (migration 0009). The
	 *  column-level CHECK constraint enforces the same bounds, so a
	 *  frontend that hand-rolls an out-of-range value gets a SQLite
	 *  constraint failure rather than silently skipping the transition.
	 */
	completionThreshold: number,
	/**
	 *  Drift tolerance in milliseconds for the multi-view sync loop.
	 *  Persisted in `app_settings.sync_drift_threshold_ms` (migration
	 *  0011); the column-level CHECK enforces `[50.0, 1000.0]`.  See
	 *  ADR-0022 for the rationale on the default of 250 ms.
	 */
	syncDriftThresholdMs: number,
	/**
	 *  Layout the multi-view page mounts when the user opens a fresh
	 *  session.  v1 only ships `Split5050`.
	 */
	syncDefaultLayout: SyncLayout,
	/**
	 *  Strategy for picking the leader pane when a session starts.
	 *  `'first-opened'` selects pane index 0 (the primary VOD the
	 *  user clicked).  Modeled as a string rather than an enum so v2
	 *  can add `'longest'` etc. without an IPC contract bump.
	 */
	syncDefaultLeader: string,
	/**
	 *  Master toggle for the auto-cleanup service. Default off
	 *  (ADR-0024); the UI confirms the plan before flipping this on.
	 */
	cleanupEnabled: boolean,
	/**
	 *  Used-fraction threshold above which the scheduled tick runs
	 *  (default 0.9, range 0.5..=0.99).
	 */
	cleanupHighWatermark: number,
	/**
	 *  Used-fraction stop threshold the cleanup run targets
	 *  (default 0.75, range 0.4..=0.95). Service-layer write enforces
	 *  `cleanup_low_watermark < cleanup_high_watermark`.
	 */
	cleanupLowWatermark: number,
	/**
	 *  Local hour of day at which the scheduled tick fires
	 *  (default 3, range 0..=23).
	 */
	cleanupScheduleHour: number,
	/**
	 *  Master toggle for the GitHub Releases update checker.
	 *  Default off (ADR-0026, privacy posture).
	 */
	updateCheckEnabled: boolean,
	/**
	 *  Wall-clock seconds at which the daily check most recently ran
	 *  (any outcome).  None when the user has just enabled the
	 *  feature.
	 */
	updateCheckLastRun: number | null,
	/**
	 *  Tag the user explicitly suppressed via "Skip this version".
	 *  Empty / cleared when the user clicks "Don't skip".
	 */
	updateCheckSkipVersion: string | null,
	/**
	 *  Chosen video-quality profile.  Default `'720p30'` for new
	 *  installs.  Persisted in `app_settings.video_quality_profile`
	 *  (migration 0015).  Distinct from the legacy `quality_preset`
	 *  field which is preserved for backwards-compat with v1.0
	 *  installs that already have a value there.
	 */
	videoQualityProfile: VideoQualityProfile,
	/**
	 *  User opt-in for the libx265 / libx264 software fallback path.
	 *  Default false; the encoder-detection pass surfaces a warning
	 *  when no hardware encoder is available and this is off.
	 */
	softwareEncodeOptIn: boolean,
	/**
	 *  Detection result from `services::encoder_detection`.  `None`
	 *  when detection has never run (cold start or after the user
	 *  clicked "Re-detect" and the call hasn't yet completed).
	 */
	encoderCapability: EncoderCapability | null,
	/**
	 *  Concurrency cap on background re-encodes.  Default 1, hard
	 *  clamped to 1..=2.
	 */
	maxConcurrentReencodes: number,
	/**
	 *  CPU-load fraction above which a sustained burst pauses the
	 *  in-flight ffmpeg encoder (ADR-0029).
	 */
	cpuThrottleHighThreshold: number,
	/**
	 *  CPU-load fraction below which a sustained idle period resumes
	 *  a paused encoder.  Strictly less than `cpu_throttle_high_threshold`
	 *  (service-layer rejects an inverted pair).
	 */
	cpuThrottleLowThreshold: number,
	/**
	 *  Default `Pull` for new installs; existing v1.0 installs are
	 *  pinned to `Auto` by migration 0017.
	 */
	distributionMode: DistributionMode,
	/**
	 *  Per-streamer cap on `(queued + downloading + ready)` rows.
	 *  Default 2; range [1, 20].
	 */
	slidingWindowSize: number,
	/**
	 *  Whether the player's prefetch hook (ADR-0031) is allowed to
	 *  auto-pick the next VOD.  Defaults to true; off = strict
	 *  pull-only, the user picks every VOD by hand.
	 */
	prefetchEnabled: boolean,
};

export type AppShutdownRequestedEvent = {
	// Deadline in unix-seconds — the services flush by this time.
	deadlineAt: number,
};

// Snapshot used by the tray popover + menu-bar tooltip.
export type AppSummary = {
	activeDownloads: number,
	queuedDownloads: number,
	bandwidthBps: number,
	/**
	 *  `None` when no streamer is due yet (empty roster). Seconds to
	 *  the next scheduled poll for any streamer.
	 */
	nextPollEtaSeconds: number | null,
	// `None` when the user has no streamers yet.
	streamerCount: number,
};

/**
 *  Tray menu → webview coordination signal. The tray handler emits a
 *  specific `kind` string; the frontend narrows on it to route UI
 *  state (e.g. focus the Downloads route, surface a pause toast).
 */
export type AppTrayActionEvent = {
	kind: string,
};

/**
 *  Mostly-data struct returned by the `cmd_get_autostart_status`
 *  command. Separate from `AppSettings.start_at_login` because the
 *  OS-observed value can diverge if the user toggled the OS setting
 *  outside Sightline.
 */
export type AutostartStatus = {
	osEnabled: boolean,
	dbEnabled: boolean,
};

export type Chapter = {
	positionMs: number,
	durationMs: number,
	gameId: string | null,
	gameName: string,
	chapterType: ChapterType,
};

export type ChapterType = "GAME_CHANGE" | "SYNTHETIC" | "OTHER";

export type CheckForUpdateInput = {
	/**
	 *  Skip the once-per-24h gate.  The Settings UI's "Check now"
	 *  button passes `true`; the scheduled tick uses `false`.
	 */
	force: boolean,
};

/**
 *  One row in a cleanup plan — a VOD the service has flagged as
 *  safe to delete.  Returned to the UI verbatim so the user can
 *  review before confirming.
 */
export type CleanupCandidate = {
	vodId: string,
	streamerLogin: string,
	streamStartedAt: number,
	lastWatchedAt: number,
	/**
	 *  Mirrors `watch_progress.state` wire strings.  Only `completed`
	 *  or `manually_watched` ever appear in a plan; the comparator
	 *  rejects anything else.
	 */
	watchState: string,
	sizeBytes: number,
	finalPath: string,
};

export type CleanupDiskPressureEvent = {
	usedFraction: number,
	freeBytes: number,
};

export type CleanupExecutedEvent = {
	mode: string,
	status: string,
	freedBytes: number,
	deletedVodCount: number,
};

export type CleanupHistoryInput = {
	/**
	 *  Maximum entries to return.  Clamped to `[1, 200]` server-side.
	 *  Default 25.
	 */
	limit?: number | null,
};

/**
 *  One row from the `cleanup_log` audit table.  The History view in
 *  Settings consumes this directly.
 */
export type CleanupLogEntry = {
	id: number,
	ranAt: number,
	mode: string,
	freedBytes: number,
	deletedVodCount: number,
	status: string,
};

export type CleanupMode = "scheduled" | "manual" | "dry_run";

/**
 *  What `compute_plan` returns: the candidates ranked in deletion
 *  order plus the disk-usage snapshot the plan was built against.
 *  `target_free_after_bytes` is non-negative even when no work is
 *  projected — `0` simply means "the plan would not delete anything",
 *  which is distinct from `candidates.is_empty() && disk pressure is
 *  below the high watermark` (status: skipped).
 */
export type CleanupPlan = {
	candidates: CleanupCandidate[],
	totalBytes: number,
	freeBytesBefore: number,
	// Sum of `size_bytes` across `candidates`.
	projectedFreedBytes: number,
	/**
	 *  Used-fraction snapshot at plan time (0.0..=1.0).  A renderer
	 *  can compare to the live watermarks without needing a separate
	 *  settings query.
	 */
	usedFractionBefore: number,
	/**
	 *  Settings snapshot used to build the plan.  Mirrored so the UI
	 *  can label the plan ("would shrink to 75 % of disk capacity").
	 */
	highWatermark: number,
	lowWatermark: number,
};

export type CleanupPlanReadyEvent = {
	candidateCount: number,
	projectedFreedBytes: number,
};

// What `execute_plan` returns once it has actually written to disk.
export type CleanupResult = {
	mode: CleanupMode,
	// Mirrors `cleanup_log.status` wire strings.
	status: string,
	freedBytes: number,
	deletedVodCount: number,
	logId: number,
};

/**
 *  Co-stream hit: another interval overlapping a reference, paired
 *  with the number of seconds of overlap (> 0).
 */
export type CoStream = {
	interval: Interval,
	overlapSeconds: number,
};

/**
 *  Items surfaced in the Continue Watching row. `remaining_seconds`
 *  is a derived convenience so the frontend doesn't have to recompute
 *  it from the stored position.
 */
export type ContinueWatchingEntry = {
	vodId: string,
	title: string,
	streamerDisplayName: string,
	streamerLogin: string,
	durationSeconds: number,
	positionSeconds: number,
	remainingSeconds: number,
	watchedFraction: number,
	thumbnailUrl: string | null,
	lastWatchedAt: number,
};

export type CredentialsChangedEvent = {
	configured: boolean,
};

export type CredentialsStatus = {
	configured: boolean,
	clientIdMasked: string | null,
	lastTokenAcquiredAt: number | null,
};

/**
 *  Live disk-usage snapshot exposed via `cmd_get_disk_usage`.  The
 *  fields land verbatim on the Settings UI's Storage section.
 */
export type DiskUsage = {
	/**
	 *  True iff the user has chosen a `library_root` in Settings.
	 *  When false, the `*_bytes` and `used_fraction` fields are zero
	 *  — the renderer renders a "no library configured" state.
	 */
	libraryRootConfigured: boolean,
	totalBytes: number,
	freeBytes: number,
	usedFraction: number,
	highWatermark: number,
	lowWatermark: number,
	aboveHighWatermark: boolean,
};

/**
 *  Distribution mode — selects between v1.0 auto-download
 *  behaviour and the v2.0 pull-on-demand model.  Persisted in
 *  `app_settings.distribution_mode` (migration 0017).  New installs
 *  default to `Pull`; existing installs are pinned to `Auto` by the
 *  migration's backward-compat detection.
 */
export type DistributionMode = 
/**
 *  v1.0 behaviour: polling auto-enqueues every newly-discovered
 *  VOD into the download queue.
 */
"auto" | 
/**
 *  v2.0 default: polling produces `available` rows; the user
 *  picks explicitly (or pre-fetch picks one VOD ahead).
 */
"pull";

export type DistributionPrefetchTriggeredEvent = {
	currentlyWatching: string,
	prefetched: string,
};

export type DistributionVodArchivedEvent = {
	vodId: string,
};

export type DistributionVodPickedEvent = {
	vodId: string,
	/**
	 *  State the row was in before the pick.  Useful for the
	 *  renderer's optimistic-update path: a `available -> queued`
	 *  transition needs different cache invalidation than a
	 *  `deleted -> queued` re-pick.
	 */
	fromStatus: string,
};

export type DistributionWindowEnforcedEvent = {
	streamerId: string,
	evictedVodId: string,
};

export type DownloadCompletedEvent = {
	vodId: string,
	finalPath: string,
};

export type DownloadFailedEvent = {
	vodId: string,
	reason: string,
};

export type DownloadFilters = {
	state?: DownloadState | null,
	streamerId?: string | null,
};

export type DownloadProgressEvent = {
	vodId: string,
	progress: number | null,
	bytesDone: number,
	bytesTotal: number | null,
	speedBps: number | null,
	etaSeconds: number | null,
};

/**
 *  A single row from the `downloads` table, joined with the owning
 *  VOD + streamer so the frontend doesn't have to round-trip.
 */
export type DownloadRow = {
	vodId: string,
	state: DownloadState,
	priority: number,
	qualityPreset: QualityPreset,
	qualityResolved: string | null,
	stagingPath: string | null,
	finalPath: string | null,
	bytesTotal: number | null,
	bytesDone: number,
	speedBps: number | null,
	etaSeconds: number | null,
	attempts: number,
	lastError: string | null,
	lastErrorAt: number | null,
	queuedAt: number,
	startedAt: number | null,
	finishedAt: number | null,
	pauseRequested: boolean,
	title: string,
	streamerDisplayName: string,
	streamerLogin: string,
	thumbnailUrl: string | null,
};

/**
 *  Every reachable state of a download. The wire string (matching the
 *  `CHECK` constraint on `downloads.state`) is stable; changing it is
 *  a schema change.
 */
export type DownloadState = "queued" | "downloading" | "paused" | "completed" | "failed_retryable" | "failed_permanent";

export type DownloadStateChangedEvent = {
	vodId: string,
	// Matches `DownloadState` wire strings.
	state: string,
};

/**
 *  One pane's drift measurement, fed back from the frontend sync
 *  loop.  The values describe a single observation; the services
 *  layer turns these into `sync:drift_corrected` events when the
 *  magnitude exceeds the configured threshold.
 */
export type DriftMeasurement = {
	paneIndex: number,
	followerPositionSeconds: number,
	expectedPositionSeconds: number,
	driftMs: number,
};

/**
 *  Detection result persisted in `app_settings.encoder_capability`
 *  as JSON.  Documented in ADR-0028 §Detection.
 */
export type EncoderCapability = {
	/**
	 *  Encoder the service will use first.  When this is
	 *  [`EncoderKind::Software`] but `software_encode_opt_in = 0`
	 *  in settings, the re-encode pass refuses to run and surfaces
	 *  an error instead.
	 */
	primary: EncoderKind,
	/**
	 *  Every encoder that passed both the `-encoders` listing AND
	 *  the runtime test encode.  Always contains [`EncoderKind::Software`]
	 *  in the fallback position because libx265 is bundled with
	 *  every ffmpeg sidecar build (ADR-0013).
	 */
	available: EncoderKind[],
	// Whether the primary encoder supports H.265.
	h265: boolean,
	// Whether the primary encoder supports H.264.
	h264: boolean,
	/**
	 *  Wall-clock seconds at which the detection ran.  Used by the
	 *  Settings UI to render "Auto-detected (NN minutes ago)".
	 */
	testedAt: number,
};

/**
 *  Hardware (or software) encoder available on this machine.  The
 *  detection service (`services::encoder_detection`) builds an
 *  [`EncoderCapability`] from running `ffmpeg -encoders` plus a
 *  2-second test encode.
 */
export type EncoderKind = "video_toolbox" | "nvenc" | "amf" | "quick_sync" | "vaapi" | "software";

export type EnqueueDownloadInput = {
	vodId: string,
	priority?: number | null,
};

export type ExecuteCleanupInput = {
	dryRun: boolean,
};

export type GetCoStreamsInput = {
	vodId: string,
};

export type GetOverlapInput = {
	vodIds: string[],
};

export type GetVodInput = {
	twitchVideoId: string,
};

export type GetWatchStatsInput = {
	streamerId?: string | null,
};

export type HealthReport = {
	// Short program identifier. Always `"sightline"`.
	appName: string,
	// Cargo package version (from `CARGO_PKG_VERSION`).
	appVersion: string,
	// SQLite `PRAGMA user_version` at the time of the call.
	schemaVersion: number,
	// Unix seconds UTC when the process started.
	startedAt: number,
	// Unix seconds UTC when this report was assembled.
	checkedAt: number,
};

// Ingest lifecycle. Matches the `CHECK` constraint on `vods.ingest_status`.
export type IngestStatus = "pending" | "chapters_fetched" | "eligible" | "skipped_game" | "skipped_sub_only" | "skipped_live" | "error";

/**
 *  A single stream's wall-clock lifetime. `start_at` / `end_at` are UTC
 *  unix seconds; the invariant `start_at <= end_at` is enforced at the
 *  DB layer (CHECK) and by `Interval::new`.
 */
export type Interval = {
	vodId: string,
	streamerId: string,
	startAt: number,
	endAt: number,
};

export type LastPollSummary = {
	startedAt: number,
	finishedAt: number | null,
	vodsNew: number,
	vodsUpdated: number,
	status: string,
};

export type LibraryInfo = {
	path: string | null,
	freeBytes: number | null,
	fileCount: number,
};

/**
 *  The two layout options surfaced on the Settings page. Wire strings
 *  match the `CHECK` constraint on `app_settings.library_layout`.
 */
export type LibraryLayoutKind = 
// Plex / Jellyfin / Infuse — one folder per streamer, Kodi NFO sidecar.
"plex" | 
/**
 *  Hidden-thumb flat layout. Minimal, no sidecars on disk beyond
 *  the video itself.
 */
"flat";

export type LibraryMigratingEvent = {
	migrationId: number,
	moved: number,
	total: number,
};

export type LibraryMigrationCompletedEvent = {
	migrationId: number,
	moved: number,
	errors: number,
};

export type LibraryMigrationFailedEvent = {
	migrationId: number,
	reason: string,
};

export type ListContinueWatchingInput = {
	limit?: number | null,
};

export type ListDownloadsInput = {
	filters?: DownloadFilters | null,
};

export type ListTimelineInput = {
	filters?: TimelineFilters | null,
};

export type ListVodsInput = {
	filters: VodFilters,
	sort: VodSort,
	limit: number,
	offset: number,
};

export type MigrateLibraryInput = {
	targetLayout: LibraryLayoutKind,
};

export type MigrateLibraryOutput = {
	migrationId: number,
};

export type MigrationIdInput = {
	migrationId: number,
};

export type MigrationRow = {
	id: number,
	startedAt: number,
	finishedAt: number | null,
	fromLayout: LibraryLayoutKind,
	toLayout: LibraryLayoutKind,
	moved: number,
	errors: number,
	status: string,
};

// A muted segment returned by the Helix `videos` endpoint.
export type MutedSegment = {
	offsetSeconds: number,
	durationSeconds: number,
};

// Notification category. Maps 1:1 to a per-user setting toggle.
export type NotificationCategory = "download_complete" | "download_failed" | "favorites_ingest" | "storage_low";

/**
 *  Payload emitted on the generic `notification:show` topic. The
 *  category-specific topic also receives a mirror so callers that
 *  care about just one category can subscribe narrowly.
 */
export type NotificationPayload = {
	category: NotificationCategory,
	title: string,
	body: string,
	/**
	 *  Optional deep-link / routing hint. The frontend interprets it
	 *  (e.g. `"/downloads?vod=…"` to focus a specific row).
	 */
	link?: string | null,
	// Count coalesced into this notification (>= 1).
	coalesced: number,
	// Emission timestamp (unix seconds UTC).
	emittedAt: number,
};

export type OpenReleaseUrlInput = {
	url: string,
};

export type OpenSyncGroupInput = {
	vodIds: string[],
	layout: SyncLayout,
};

/**
 *  Snapshot exposed via `cmd_get_overlap` and `cmd_open_sync_group`'s
 *  pre-validation.  Wraps [`OverlapWindow`] with the input vod_ids
 *  echoed back so the renderer can correlate without an extra query.
 */
export type OverlapResult = {
	vodIds: string[],
	window: OverlapWindow,
};

/**
 *  Wall-clock window every member of a sync group has video for.  The
 *  `/multiview` route uses this to bound its seek slider.
 */
export type OverlapWindow = {
	// Maximum of all members' `stream_started_at`s.
	startAt: number,
	// Minimum of all members' (`stream_started_at + duration`)s.
	endAt: number,
};

export type PickNextNInput = {
	streamerId: string,
	n: number,
};

/**
 *  Result of a `pick_vod` / `unpick_vod` call.  Carries the new
 *  status so the renderer can update its cache without a re-fetch.
 */
export type PickResult = {
	vodId: string,
	status: VodStatus,
};

export type PickVodInput = {
	vodId: string,
};

export type PollFinishedEvent = {
	twitchUserId: string,
	finishedAt: number,
	vodsNew: number,
	vodsUpdated: number,
	status: string,
};

export type PollStartedEvent = {
	twitchUserId: string,
	startedAt: number,
};

export type PollStatusRow = {
	streamer: StreamerSummary,
	lastPoll: LastPollSummary | null,
};

// The four presets exposed on the UI. Wire strings are stable.
export type QualityPreset = 
// Best video + best audio, whatever the source offers.
"source" | 
// 1080p60 or less.
"1080p60" | 
// 720p60 or less.
"720p60" | 
// 480p or less, 30fps cap implied.
"480p";

export type RecordSyncDriftInput = {
	sessionId: number,
	measurement: DriftMeasurement,
};

export type RemoveStreamerInput = {
	twitchUserId: string,
};

export type ReportSyncOutOfRangeInput = {
	sessionId: number,
	paneIndex: number,
};

export type ReprioritizeInput = {
	vodId: string,
	priority: number,
};

export type SetAutostartInput = {
	enabled: boolean,
};

export type SetDistributionModeInput = {
	mode: DistributionMode,
};

export type SetShortcutInput = {
	actionId: string,
	keys: string,
};

export type SetSlidingWindowSizeInput = {
	size: number,
};

export type SetSyncLeaderInput = {
	sessionId: number,
	paneIndex: number,
};

/**
 *  Input payload for `set_twitch_credentials`. The IPC boundary is
 *  the only place the Client Secret crosses from the webview into
 *  Rust; any `{:?}` downstream of that would risk logging it, so
 *  `Debug` is redacted.
 */
export type SetTwitchCredentialsInput = {
	clientId: string,
	clientSecret: string,
};

/**
 *  Persist the chosen quality profile.  Wraps `update_settings` for
 *  the typed-from-the-renderer "user picked a profile" gesture; the
 *  generic `update_settings` command also accepts the field through
 *  `SettingsPatch.video_quality_profile`, but a dedicated command
 *  keeps the IPC surface readable on the Settings UI side.
 */
export type SetVideoQualityProfileInput = {
	profile: VideoQualityProfile,
};

export type SetWindowCloseBehaviorInput = {
	behavior: WindowCloseBehavior,
};

/**
 *  Partial settings update — any subset may be supplied by the frontend.
 * 
 *  `#[specta(optional)]` on each `Option<T>` field makes tauri-specta
 *  emit `T?: T` rather than `T | null` required keys, so the frontend
 *  can pass literal `{ enabledGameIds: ... }` objects without having to
 *  spread a full "empty patch" baseline. See ADR-0009.
 */
export type SettingsPatch = {
	enabledGameIds?: string[] | null,
	pollFloorSeconds?: number | null,
	pollRecentSeconds?: number | null,
	pollCeilingSeconds?: number | null,
	concurrencyCap?: number | null,
	firstBackfillLimit?: number | null,
	libraryRoot?: string | null,
	libraryLayout?: LibraryLayoutKind | null,
	stagingPath?: string | null,
	maxConcurrentDownloads?: number | null,
	/**
	 *  Sentinel: provide `Some(n)` to set a cap, or `Some(-1)` to
	 *  clear (unlimited). Omit to leave unchanged.
	 */
	bandwidthLimitBps?: number | null,
	qualityPreset?: QualityPreset | null,
	autoUpdateYtDlp?: boolean | null,
	windowCloseBehavior?: WindowCloseBehavior | null,
	startAtLogin?: boolean | null,
	showDockIcon?: boolean | null,
	notificationsEnabled?: boolean | null,
	notifyDownloadComplete?: boolean | null,
	notifyDownloadFailed?: boolean | null,
	notifyFavoritesIngest?: boolean | null,
	notifyStorageLow?: boolean | null,
	completionThreshold?: number | null,
	syncDriftThresholdMs?: number | null,
	syncDefaultLayout?: SyncLayout | null,
	syncDefaultLeader?: string | null,
	cleanupEnabled?: boolean | null,
	cleanupHighWatermark?: number | null,
	cleanupLowWatermark?: number | null,
	cleanupScheduleHour?: number | null,
	updateCheckEnabled?: boolean | null,
	/**
	 *  Pass an empty string to clear; pass `Some("v1.2.3")` to skip
	 *  that release.  Omit to leave unchanged.
	 */
	updateCheckSkipVersion?: string | null,
	videoQualityProfile?: VideoQualityProfile | null,
	softwareEncodeOptIn?: boolean | null,
	maxConcurrentReencodes?: number | null,
	cpuThrottleHighThreshold?: number | null,
	cpuThrottleLowThreshold?: number | null,
	distributionMode?: DistributionMode | null,
	slidingWindowSize?: number | null,
	prefetchEnabled?: boolean | null,
};

/**
 *  Freeform key → keystroke map. The frontend owns the canonical list
 *  of action IDs (e.g. `library`, `timeline`, `focus_search`, …); the
 *  backend just persists the chosen keystrokes so they survive
 *  restarts. We store the serialized map as a JSON string under a
 *  single row in a dedicated table.
 */
export type Shortcut = {
	actionId: string,
	keys: string,
};

export type SkipUpdateVersionInput = {
	// Empty string clears any prior skip.
	version: string,
};

export type StagingInfo = {
	path: string,
	freeBytes: number,
	staleFileCount: number,
};

export type StorageLowDiskWarningEvent = {
	path: string,
	freeBytes: number,
};

// Storage-aligned streamer row. The `*_at` fields are unix seconds UTC.
export type Streamer = {
	twitchUserId: string,
	login: string,
	displayName: string,
	profileImageUrl: string | null,
	broadcasterType: string,
	twitchCreatedAt: number,
	addedAt: number,
	deletedAt: number | null,
	lastPolledAt: number | null,
	nextPollAt: number | null,
	lastLiveAt: number | null,
	/**
	 *  Phase 4: user-flagged favourite, drives the "new VODs from
	 *  favorites" notification category.
	 */
	favorite?: boolean,
};

export type StreamerAddedEvent = {
	twitchUserId: string,
	login: string,
};

export type StreamerFavoritedEvent = {
	twitchUserId: string,
};

export type StreamerRemovedEvent = {
	twitchUserId: string,
};

// Frontend-facing summary: the `Streamer` row plus derived fields.
export type StreamerSummary = {
	streamer: Streamer,
	vodCount: number,
	eligibleVodCount: number,
	liveNow: boolean,
	nextPollEtaSeconds: number | null,
};

export type StreamerUnfavoritedEvent = {
	twitchUserId: string,
};

export type SyncDriftCorrectedEvent = {
	sessionId: number,
	paneIndex: number,
	driftMs: number,
	correctedToSeconds: number,
};

export type SyncGroupClosedEvent = {
	sessionId: number,
};

/**
 *  Layout vocabulary mirroring `sync_sessions.layout`.  v1 only ships
 *  one variant; the enum exists so the frontend's `MultiViewPage` can
 *  switch on the discriminant when v2 adds PiP / 2x2 grid options.
 */
export type SyncLayout = 
// Two panes, fixed 50/50 horizontal split.  ADR-0021.
"split-50-50";

export type SyncLeaderChangedEvent = {
	sessionId: number,
	leaderPaneIndex: number,
};

/**
 *  One pane's membership inside a session.  Mirrors a
 *  `sync_session_panes` row plus the joined `vod_id` in raw form
 *  (the services layer dereferences it via `vods` for any UI surface
 *  that wants the title / streamer).
 */
export type SyncMember = {
	paneIndex: number,
	vodId: string,
	volume: number,
	muted: boolean,
	joinedAt: number,
};

export type SyncMemberOutOfRangeEvent = {
	sessionId: number,
	paneIndex: number,
};

export type SyncSeekInput = {
	sessionId: number,
	wallClockTs: number,
};

// Snapshot of a sync session as exposed to the frontend.
export type SyncSession = {
	id: number,
	createdAt: number,
	closedAt: number | null,
	layout: SyncLayout,
	/**
	 *  `None` only during the brief window between a session's
	 *  `INSERT` and the follow-up `UPDATE` that sets the leader. The
	 *  services layer never returns a `None` leader to the frontend
	 *  — the open path is a single transaction.
	 */
	leaderPaneIndex: number | null,
	status: SyncStatus,
	panes: SyncMember[],
};

export type SyncSessionIdInput = {
	sessionId: number,
};

export type SyncSetSpeedInput = {
	sessionId: number,
	speed: number,
};

export type SyncStateChangedEvent = {
	sessionId: number,
	// Mirrors `SyncStatus` db strings (`active` | `closed`).
	status: string,
};

/**
 *  Lifecycle of a `sync_sessions` row.  `Active` is the steady state;
 *  `Closed` is terminal — no transitions back, by design.
 */
export type SyncStatus = "active" | "closed";

/**
 *  Filter predicate for the `list_timeline` read. Each field is
 *  independently optional; `None` means "no filter on this axis".
 */
export type TimelineFilters = {
	since?: number | null,
	until?: number | null,
	streamerIds?: string[] | null,
};

export type TimelineIndexRebuildingEvent = {
	// Fraction complete in [0.0, 1.0].
	progress: number,
	processed: number,
	total: number,
};

export type TimelineIndexRebuiltEvent = {
	total: number,
};

// Timeline stats for the header of the `/timeline` route.
export type TimelineStats = {
	totalIntervals: number,
	earliestStartAt: number | null,
	latestEndAt: number | null,
	largestOverlapGroup: number,
};

export type ToggleFavoriteInput = {
	streamerId: string,
};

export type TrayActionInput = {
	/**
	 *  Closed-set action identifier. Rejected at deserialization if the
	 *  caller supplies an unknown value.
	 */
	kind: TrayActionKind,
};

/**
 *  Closed set of tray menu actions. Adding a new action means:
 *    1. Add a variant here.
 *    2. Handle it in the frontend `AppShell`'s `app:tray_action` switch.
 *    3. Wire the tray menu item to call `emit_tray_action({ kind })`.
 * 
 *  Serialized as snake_case over IPC so the JSON wire form is stable
 *  against Rust-side renames.
 */
export type TrayActionKind = "open_sightline" | "open_library" | "open_timeline" | "open_downloads" | "open_settings" | "pause_all" | "resume_all";

export type TriggerPollInput = {
	// If omitted, the poller re-evaluates every due streamer on its next tick.
	twitchUserId: string | null,
};

/**
 *  Surfaced to the renderer.  `version` is normalised (no leading
 *  `v`) so the UI can compare against `process.env.npm_package_version`
 *  equivalents directly.
 */
export type UpdateInfo = {
	version: string,
	releaseUrl: string,
	body: string,
	publishedAt: number | null,
};

export type UpdateStatus = {
	enabled: boolean,
	currentVersion: string,
	lastCheckedAt: number | null,
	skipVersion: string | null,
	available: UpdateInfo | null,
};

export type UpdateWatchProgressInput = {
	vodId: string,
	positionSeconds: number,
	durationSeconds: number,
};

export type UpdaterCheckFailedEvent = {
	reason: string,
};

export type UpdaterUpdateAvailableEvent = {
	version: string,
	releaseUrl: string,
	body: string,
};

/**
 *  User-facing quality profile.  The wire strings are the strings we
 *  persist in `app_settings.video_quality_profile`; do not rename
 *  them without a migration.
 */
export type VideoQualityProfile = "480p30" | "480p60" | "720p30" | "720p60" | "1080p30" | "1080p60" | "source";

/**
 *  Single-choke-point answer for `<video src>`. The player uses this
 *  to decide which state to render — the happy path (`ready`), the
 *  "file moved / deleted externally" path (`missing`), or the
 *  partial-download path (`partial`, download not finished yet).
 */
export type VideoSource = {
	vodId: string,
	/**
	 *  `None` when state != "ready". Always absolute and verified to
	 *  sit inside the library root.
	 */
	path: string | null,
	state: VideoSourceState,
};

export type VideoSourceState = "ready" | "missing" | "partial";

// Storage-aligned VOD row. The `*_at` fields are unix seconds UTC.
export type Vod = {
	twitchVideoId: string,
	twitchUserId: string,
	streamId: string | null,
	title: string,
	description: string,
	streamStartedAt: number,
	publishedAt: number,
	url: string,
	thumbnailUrl: string | null,
	durationSeconds: number,
	viewCount: number,
	language: string,
	mutedSegments: MutedSegment[],
	isSubOnly: boolean,
	helixGameId: string | null,
	helixGameName: string | null,
	ingestStatus: IngestStatus,
	statusReason: string,
	firstSeenAt: number,
	lastSeenAt: number,
};

/**
 *  Renderer-facing bundle of per-VOD asset paths. Every `path` is an
 *  absolute filesystem string; the frontend passes each through
 *  `convertFileSrc`.
 */
export type VodAssets = {
	vodId: string,
	/**
	 *  Path to the `.mp4` under the library root if the download has
	 *  completed; `None` otherwise.
	 */
	videoPath: string | null,
	// Single-frame thumbnail from the Phase-3 pipeline.
	thumbnailPath: string | null,
	/**
	 *  Ordered list of six hover-preview frames. Empty if the preview
	 *  set is missing (pre-Phase-5 download that hasn't been backfilled
	 *  yet, or an ffmpeg failure).
	 */
	previewFramePaths: string[],
};

export type VodAssetsInput = {
	vodId: string,
};

/**
 *  VOD list filter. Every field is optional; omitted keys mean
 *  "no constraint". `#[specta(optional)]` ensures the TS emission is
 *  `T?: T` rather than `T | null` required keys — see ADR-0009.
 */
export type VodFilters = {
	streamerIds?: string[] | null,
	// Mirrors `IngestStatus` db strings; caller may send any subset.
	statuses?: string[] | null,
	gameIds?: string[] | null,
	// Unix seconds UTC.
	since?: number | null,
	until?: number | null,
};

export type VodIdInput = {
	vodId: string,
};

export type VodIngestedEvent = {
	twitchVideoId: string,
	twitchUserId: string,
	// Mirrors `vods.ingest_status`.
	ingestStatus: string,
	streamStartedAt: number,
};

export type VodSort = "stream_started_at_desc" | "stream_started_at_asc";

/**
 *  Lifecycle state of a single VOD row in the distribution model.
 *  Persisted as `vods.status` (migration 0016).  CHECK constraint
 *  in the migration file enforces the same closed set.
 */
export type VodStatus = 
// Polled by the background, metadata only — file not on disk.
"available" | 
/**
 *  User picked this VOD (or pre-fetch did); waiting for a
 *  download worker.
 */
"queued" | 
// Download in flight.
"downloading" | 
// File on disk, ready to play.
"ready" | 
/**
 *  Watched (`watch_progress.state ∈ {completed, manually_watched}`)
 *  — eligible for sliding-window cleanup.
 */
"archived" | 
/**
 *  Cleanup deleted the file.  Row stays so the user can re-pick
 *  for a fresh download.
 */
"deleted";

export type VodUpdatedEvent = {
	twitchVideoId: string,
	ingestStatus: string,
};

export type VodWithChapters = {
	vod: Vod,
	chapters: Chapter[],
	// Streamer display name, denormalized for convenience.
	streamerDisplayName: string,
	streamerLogin: string,
};

export type WatchCompletedEvent = {
	vodId: string,
};

/**
 *  Public snapshot of a VOD's watch progress — serialised to the
 *  frontend via IPC and included in the Continue Watching row.
 */
export type WatchProgressRow = {
	vodId: string,
	positionSeconds: number,
	durationSeconds: number,
	watchedFraction: number,
	state: WatchState,
	firstWatchedAt: number | null,
	lastWatchedAt: number,
	lastSessionDurationSeconds: number,
	totalWatchSeconds: number,
};

export type WatchProgressUpdatedEvent = {
	vodId: string,
	positionSeconds: number,
	// Mirrors `WatchState` db strings.
	state: string,
};

/**
 *  Canonical watch state. Wire strings match the CHECK constraint in
 *  migration 0008.
 */
export type WatchState = "unwatched" | "in_progress" | "completed" | "manually_watched";

export type WatchStateChangedEvent = {
	vodId: string,
	from: string,
	to: string,
};

/**
 *  Aggregate stats used by the later "hours watched this streamer"
 *  summaries. Defined now so the command + binding types are stable.
 */
export type WatchStats = {
	totalWatchSeconds: number,
	completedCount: number,
	inProgressCount: number,
};

/**
 *  Distinct from `crate::commands::downloads::VodIdInput` (downloads)
 *  and `crate::commands::media::VodAssetsInput` so tauri-specta
 *  doesn't collide on the type-name when emitting the bindings. The
 *  wire shape is identical.
 */
export type WatchVodIdInput = {
	vodId: string,
};

/**
 *  What happens when the user clicks the window close button.
 * 
 *  - `Hide` (default, new Phase-4 behaviour): the window is hidden,
 *    poller + download queue keep running, tray stays on.
 *  - `Quit`: explicit quit. Tokio services drain gracefully and the
 *    process exits.
 */
export type WindowCloseBehavior = "hide" | "quit";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

