// AUTO-GENERATED — DO NOT EDIT.
// Regenerated on every `pnpm tauri dev` (debug) and via
// `cargo test --test ipc_bindings` (CI drift check). See
// docs/adr/0007-ipc-typegen.md.

/* eslint-disable */

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**
	 *  Returns an application health report.
	 * 
	 *  Used by the frontend on startup to verify that the webview, command
	 *  bridge, and database are all alive.
	 */
	health: () => typedError<HealthReport, AppError>(__TAURI_INVOKE("health")),
};

/* Types */
/**
 *  Typed application error. Serialized with a `kind` tag so the frontend
 *  can exhaustively narrow on it via a discriminated union.
 */
export type AppError = { kind: "db"; detail: string } | { kind: "io"; detail: string } | { kind: "invalid_input"; detail: string } | { kind: "not_found" } | { kind: "internal"; detail: string } | 
// Credentials-related failure (keychain read/write, missing creds, invalid input shape).
{ kind: "credentials"; detail: string } | 
// Twitch App Access Token acquisition / refresh failed.
{ kind: "twitch_auth"; detail: string } | 
/**
 *  Twitch rate limit hit. `retry_after_seconds` is a conservative hint
 *  derived from the `Ratelimit-Reset` header (or a policy floor).
 */
{ kind: "twitch_rate_limit"; retry_after_seconds: number } | 
// Generic Twitch Helix API error (non-rate-limit HTTP failure).
{ kind: "twitch_api"; status: number; detail: string } | 
// Helix returned 404 / empty set for a user or video that should exist.
{ kind: "twitch_not_found"; detail: string } | 
/**
 *  Twitch GraphQL endpoint failure. Separately typed so the UI can
 *  surface "chapters unavailable" differently from Helix failures.
 */
{ kind: "twitch_gql"; detail: string } | 
// VOD ingest pipeline failure (persistence, chapter merge, etc.).
{ kind: "ingest"; detail: string } | 
// Parser failure — duration, chapter payload, ISO timestamp.
{ kind: "parse"; detail: string };

export type HealthReport = {
	// Short program identifier. Always `"sightline"`.
	appName: string,
	// Cargo package version (from `CARGO_PKG_VERSION`).
	appVersion: string,
	// SQLite `PRAGMA user_version` at the time of the call.
	schemaVersion: number,
	// Unix seconds UTC when the process started.
	startedAt: number,
	// Unix seconds UTC when this report was assembled.
	checkedAt: number,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

